leak_sensors_simulated:
  ros__parameters:
    leak_topic: /cirtesub/leak_sensors
    publish_period: 1.0
    sensor_frames:
      - cirtesub/main_cylinder
      - cirtesub/battery_cylinder
    leak_detected:
      - false
      - false
    leak_detected_0: false
    leak_detected_1: false
